# Generated by Django 5.1.7 on 2025-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical & Electronic Engineering'), ('BBA', 'Business Administration'), ('ENG', 'English Literature'), ('LLB', 'Law')], default='CSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
